### ISSUE TITLE
Add node installation step in CI

### ISSUE THREAD

**Issue by vikas-kyatannawar** [OsmosysSoftware/dev-standards#31]
Add node installation step  with specific node version in angular CI Setup or any node project.

https://github.com/OsmosysSoftware/dev-standards/blob/main/ci-setups/angular-github.md

```yaml
name: Standard Angular App Flow

on:
  pull_request:
    branches: [ "main", "development" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
```
